# Name of your application. Used to uniquely configure containers.
service: <your-service-name>

# Name of the container image.
image: <your-username>/<your-service-name>

# Deploy to these servers.
servers:
  web:
    - <your-server-ip-address>

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: <your-host>

# Credentials for your image host.
registry:
  username: <your-username>
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

env:
  secret:
    - TELEGRAM_BOT_TOKEN
    - TELEGRAM_CHAT_ID
    - GITHUB_APP_PRIVATE_KEY
    - GITHUB_APP_ID
    - GITHUB_APP_INSTALLATION_ID

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
#
# aliases:
#   shell: app exec --interactive --reuse "bash"

# Use a different ssh user than root
ssh:
  user: <please-dont-use-root-set-up-a-custom-user-to-connect-through-ssh>
